import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'fr' | 'en' | 'es' | 'it' | 'pt';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const languages: { code: Language; name: string; flag: string }[] = [
  { code: 'fr', name: 'Français', flag: '🇫🇷' },
  { code: 'en', name: 'English', flag: '🇬🇧' },
  { code: 'es', name: 'Español', flag: '🇪🇸' },
  { code: 'it', name: 'Italiano', flag: '🇮🇹' },
  { code: 'pt', name: 'Português', flag: '🇧🇷' },
];

const translations: Record<Language, Record<string, string>> = {
  fr: {
    // Navigation
    'nav.hotel': "L'Hôtel",
    'nav.home': 'Accueil',
    'nav.rooms': 'Nos Chambres',
    'nav.breakfast': 'Petit-déjeuner',
    'nav.seminars': 'Séminaires',
    'nav.location': 'Localisation',
    'nav.events': 'Événements',
    'nav.contact': 'Contact',
    'nav.book': 'Réserver',
    
    // Hero
    'hero.welcome': 'Bienvenue',
    'hero.name': 'Hôtel Inn Design',
    'hero.location': "Place d'Italie",
    
    // Intro
    'intro.badge': 'Bienvenue',
    'intro.title': 'Un hôtel bien placé pour tout faire !',
    'intro.description': "Situé au cœur du 13ᵉ arrondissement, l'Hôtel Inn Design Paris bénéficie d'un emplacement idéal, à proximité de la Butte-aux-Cailles, des parcs et des quais. Notre hôtel propose 70 chambres confortables, un parking privé et sécurisé, ainsi qu'un bar convivial et un espace d'accueil propice à la détente ou aux échanges professionnels.",
    'intro.cta': 'Réservez votre chambre et profitez de votre séjour à Paris !',
    'intro.button': 'Réserver une chambre',
    'intro.stars': '3 étoiles',
    'intro.rooms': '70 chambres',
    'intro.parking': 'Parking privé',
    'intro.bar': 'Bar convivial',
    
    // Rooms Section (Homepage)
    'rooms.badge': 'Nos Hébergements',
    'rooms.title': 'Chambres & Suites',
    'rooms.subtitle': 'Posez vos valises et profitez !',
    'rooms.description': 'Installez-vous dans l\'une de nos 70 chambres lumineuses, insonorisées et entièrement équipées pour votre confort.',
    'rooms.description2': 'Climatisation, TV écran plat, espace bureau, coffre-fort, sèche-cheveux, plateau de courtoisie… tout est pensé pour vous.',
    'rooms.viewAll': 'Voir toutes nos chambres',
    'rooms.book': 'Réserver une chambre',
    'rooms.double': 'Chambre Double',
    'rooms.double.desc': 'Lit de 160×200 cm. Profitez d\'un espace élégant et confortable, idéal pour un séjour en couple ou en solo.',
    'rooms.twin': 'Chambre Twin',
    'rooms.twin.desc': '2 lits de 100×200 cm. Parfaite pour les voyages entre amis ou collègues, avec tout le confort nécessaire.',
    'rooms.superior': 'Chambre supérieure avec balcon',
    'rooms.superior.desc': 'Profitez d\'un espace extérieur privé avec vue sur Paris. Une expérience unique au cœur de la ville.',
    'rooms.connecting': 'Chambres Communicantes',
    'rooms.connecting.desc': '2 chambres modulables avec portes communicantes. La solution idéale pour les familles ou groupes.',
    'rooms.bathroom': 'Salle d\'eau privative',
    'rooms.tv': 'TV écran plat',
    'rooms.desk': 'Espace bureau',
    'rooms.wifi': 'Wi-Fi gratuit',
    'rooms.courtesy': 'Plateau de courtoisie',
    'rooms.ac': 'Climatisation',
    
    // Rooms Page
    'roomsPage.badge': 'Nos Hébergements',
    'roomsPage.title': 'Les chambres de l\'Hôtel Inn Design Paris',
    'roomsPage.intro': 'Profitez de 70 chambres lumineuses, insonorisées et tout confort, avec salle de bain équipée. En solo, en famille ou entre amis, tout est pensé pour votre bien-être, avec des chambres communicantes et une équipe aux petits soins. Idéalement situé, l\'hôtel est le point de départ parfait pour découvrir Paris sans stress.',
    'roomsPage.ourRooms': 'Nos hébergements',
    'roomsPage.discover': 'Découvrez nos chambres',
    'roomsPage.gallery': 'Galerie Photo',
    'roomsPage.spaces': 'Découvrez nos espaces',
    'roomsPage.view': 'Voir',
    'roomsPage.cta.title': 'Réservez votre chambre dès maintenant',
    'roomsPage.cta.subtitle': 'Profitez de -15% en réservant directement sur notre site',
    'roomsPage.cta.button': 'Voir les disponibilités',
    'roomsPage.double.name': 'Chambre Double',
    'roomsPage.double.details': 'Lit de 160×200 cm',
    'roomsPage.double.desc': 'Profitez d\'un espace élégant et confortable, idéal pour un séjour en couple ou en solo. Équipée de tout le confort moderne, cette chambre vous offre un havre de paix au cœur de Paris.',
    'roomsPage.twin.name': 'Chambre Twin',
    'roomsPage.twin.details': '2 lits de 100×200 cm',
    'roomsPage.twin.desc': 'Parfaite pour les voyages entre amis ou collègues, avec tout le confort nécessaire. Deux lits séparés dans un espace optimisé pour un séjour agréable.',
    'roomsPage.superior.name': 'Chambre Supérieure avec Balcon',
    'roomsPage.superior.details': 'Vue sur Paris',
    'roomsPage.superior.desc': 'Profitez d\'un espace extérieur privé avec vue sur Paris. Une expérience unique au cœur de la ville. Idéale pour savourer votre petit-déjeuner en admirant les toits parisiens.',
    'roomsPage.connecting.name': 'Chambres Communicantes',
    'roomsPage.connecting.details': '2 chambres modulables',
    'roomsPage.connecting.desc': 'Deux chambres avec portes communicantes, la solution idéale pour les familles ou groupes. Profitez de l\'intimité de chambres séparées tout en restant connectés.',
    
    // About / Location (Homepage)
    'about.badge': 'Emplacement idéal',
    'about.title': 'Un hôtel situé au cœur de Paris',
    'about.description': 'Hôtel Inn Paris est situé à 2min à pied du métro parisien et offre une grande commodité.',
    'about.metro': 'Accès métro (sortie 3)',
    
    // Location Section (Homepage)
    'location.badge': 'Comment nous trouver',
    'location.title': 'Localisation',
    'location.access': 'Accès',
    'location.metro': 'Métro',
    'location.bus': 'Bus',
    'location.tramway': 'Tramway',
    'location.parking': 'Parking privé sécurisé disponible sur réservation.',
    
    // Location Page
    'locationPage.badge': 'Nous trouver',
    'locationPage.title': 'Notre emplacement',
    'locationPage.openMaps': 'Ouvrir dans Google Maps',
    'locationPage.idealLocation': 'Idéalement situé',
    'locationPage.heartOfParis': 'Un hôtel au cœur de Paris',
    'locationPage.heartDesc': 'À deux pas du métro Place d\'Italie, profitez d\'un accès rapide à tous les monuments et attractions de la capitale.',
    'locationPage.parking': 'Parking',
    'locationPage.parkingDesc': 'Parking privé sécurisé (15€/jour)',
    'locationPage.reception': 'Réception',
    'locationPage.receptionDesc': 'Ouverte 24h/24',
    'locationPage.needDirections': 'Besoin d\'indications ?',
    'locationPage.airport.cdg': 'Aéroport Paris-CDG',
    'locationPage.airport.orly': 'Aéroport Paris-Orly',
    'locationPage.eiffel': 'Tour Eiffel',
    'locationPage.louvre': 'Musée du Louvre',
    'locationPage.champs': 'Champs-Élysées',
    'locationPage.pantheon': 'Le Panthéon',
    
    // Breakfast (Homepage)
    'breakfast.badge': 'À votre service',
    'breakfast.title': 'Petit-déjeuner & Bar',
    'breakfast.subtitle': 'Le petit déjeuner qui donne le sourire !',
    'breakfast.desc1': 'Chaque matin, faites le plein d\'énergie avec notre petit déjeuner complet, servi en buffet sucré & salé à volonté.',
    'breakfast.desc2': 'Au menu : boissons chaudes, baguettes tradition et céréales, viennoiseries croustillantes, fruits frais et céréales. Côté salé, retrouvez œufs durs, charcuterie, blanc de dinde, fromages et yaourts nature bio. Et pour les plus gourmands : confitures et crêpes moelleuses délicatement vanillées.',
    'breakfast.cta': 'Découvrir notre petit-déjeuner',
    'breakfast.bar.title': 'Un bar convivial pour se détendre',
    'breakfast.bar.desc1': 'À tout moment de la journée, installez-vous au bar de l\'hôtel pour partager un verre, échanger ou simplement faire une pause.',
    'breakfast.bar.desc2': 'Dans une ambiance accueillante et décontractée, c\'est l\'endroit idéal pour se retrouver après une journée bien remplie.',
    
    // Breakfast Page
    'breakfastPage.badge': 'Chaque matin',
    'breakfastPage.title': 'Le petit déjeuner qui donne le sourire !',
    'breakfastPage.intro1': 'Chaque matin, faites le plein d\'énergie avec notre petit déjeuner complet, servi en buffet sucré & salé à volonté.',
    'breakfastPage.intro2': 'Au menu : boissons chaudes, baguettes tradition et céréales, viennoiseries croustillantes, fruits frais et céréales. Côté salé, retrouvez œufs durs, charcuterie, blanc de dinde, fromages et yaourts nature bio. Et pour les plus gourmands : confitures et crêpes moelleuses délicatement vanillées.',
    'breakfastPage.enjoy': 'De quoi bien commencer la journée, quel que soit votre programme !',
    'breakfastPage.hours': 'Horaires',
    'breakfastPage.hoursValue': '7h00 - 10h00',
    'breakfastPage.formula': 'Formule',
    'breakfastPage.formulaValue': 'Buffet à volonté',
    'breakfastPage.hotDrinks': 'Boissons chaudes',
    'breakfastPage.pastries': 'Viennoiseries',
    'breakfastPage.fruits': 'Fruits frais',
    'breakfastPage.savory': 'Buffet salé',
    'breakfastPage.gallery': 'Galerie Photo',
    'breakfastPage.space': 'Notre espace petit déjeuner',
    'breakfastPage.view': 'Voir',
    
    // Seminars (Homepage)
    'seminars.badge': 'Espace professionnel',
    'seminars.title': 'Salle de séminaire',
    'seminars.subtitle': 'Organisez vos réunions autrement !',
    'seminars.desc1': 'L\'hôtel Inn Design de Paris met à votre disposition plusieurs salles de séminaire modernes et entièrement équipées : paperboard, écrans avec vidéoprojecteur, micros et connexion wifi.',
    'seminars.desc2': 'Selon vos objectifs, différentes configurations sont possibles afin de s\'adapter parfaitement à vos réunions, formations ou événements professionnels.',
    'seminars.quote': 'Demander un devis',
    'seminars.discover': 'Découvrir nos salles',
    
    // Seminars Page
    'seminarsPage.badge': 'Séminaires & Événements',
    'seminarsPage.title': 'Nos salles de séminaires',
    'seminarsPage.intro1': 'Organisez vos réunions, formations ou événements professionnels dans nos salles modernes et modulables, parfaites pour petites équipes ou grandes délégations.',
    'seminarsPage.intro2': 'Après une journée productive, vos participants pourront profiter de chambres confortables et d\'espaces de détente.',
    'seminarsPage.intro3': 'Nous proposons également des salons modulables pour vos cocktails, banquets ou journées d\'études, le tout dans un cadre pratique et agréable.',
    'seminarsPage.equipment': 'Équipements inclus',
    'seminarsPage.projector': 'Vidéoprojecteur',
    'seminarsPage.screen': 'Écran de projection',
    'seminarsPage.wifi': 'Wi-Fi haut débit',
    'seminarsPage.coffee': 'Pauses café',
    'seminarsPage.modular': 'Configurations modulables',
    'seminarsPage.catering': 'Service traiteur',
    'seminarsPage.spaces': 'Nos espaces',
    'seminarsPage.meetingRooms': 'Salles de réunion',
    'seminarsPage.virtualTour': 'Visite Virtuelle',
    'seminarsPage.videoTitle': 'Découvrez nos espaces en vidéo',
    'seminarsPage.cta.title': 'Demandez un devis personnalisé',
    'seminarsPage.cta.subtitle': 'Notre équipe vous accompagne dans l\'organisation de votre événement',
    'seminarsPage.cta.button': 'Nous contacter',
    'seminarsPage.uShape': 'En U',
    'seminarsPage.classroom': 'Classe',
    'seminarsPage.theatre': 'Théâtre',
    
    // Events
    'events.badge': 'Événements & Offres',
    'events.title': 'Découvrez notre agenda et offres',
    'events.cta': 'Voir tous les événements',
    
    // Actualites Page
    'actualites.hero.badge': 'Événements & Offres',
    'actualites.hero.title': 'Nos événements et offres exclusives',
    'actualites.hero.description': 'Découvrez les événements à venir, concerts, promotions et offres spéciales de l\'Hôtel Inn Design Paris.',
    'actualites.readTime': 'de lecture',
    'actualites.learnMore': 'En savoir plus',
    'actualites.allEvents': 'Tous les événements',
    'actualites.loadMore': 'Voir plus d\'événements',
    'actualites.newsletter.title': 'Restez informé',
    'actualites.newsletter.description': 'Inscrivez-vous à notre newsletter pour recevoir nos dernières actualités et offres exclusives.',
    'actualites.newsletter.placeholder': 'Votre email',
    'actualites.newsletter.button': 'S\'inscrire',
    'actualites.upcoming': 'À venir',
    'actualites.dontMiss': 'Nos événements à ne pas manquer',
    'actualites.concert': 'Concert solidaire',
    'actualites.enfoires.subtitle': 'La Ballade des Enfoirés - Le rendez-vous musical caritatif de l\'année',
    'actualites.enfoires.date': '13 - 19 janvier 2026',
    'actualites.enfoires.location': 'Accor Arena Paris',
    'actualites.rugby.title': 'France vs Irlande',
    'actualites.rugby.subtitle': 'Le choc au sommet du Tournoi - Vivez l\'intensité du rugby international',
    'actualites.rugby.date': '8 mars 2025',
    'actualites.rugby.location': 'Stade de France',
    'actualites.agriculture.title': 'Salon de l\'Agriculture',
    'actualites.agriculture.subtitle': 'La plus grande ferme de France - 600 000 visiteurs chaque année',
    'actualites.agriculture.date': '22 fév - 2 mars 2025',
    'actualites.agriculture.location': 'Porte de Versailles',
    'actualites.pastEvents': 'Événements passés',
    'actualites.flashback': 'Retour en images',
    'actualites.pastEventsDesc': 'Découvrez les moments partagés par nos clients lors des grands événements parisiens',
    'actualites.photosComing': 'Photos à venir prochainement...',
    
    // News Section (Homepage)
    'news.dontMiss': 'Ne manquez pas !',
    'news.upcomingEvents': 'Événements à venir',
    'news.subtitle': 'Réservez votre séjour pour les grands rendez-vous parisiens',
    'news.discover': 'Découvrir',
    'news.see': 'Voir',
    
    // Enfoires Page
    'enfoires.restosCoeur': 'Les Restos du Cœur',
    'enfoires.title': 'Les Enfoirés 2026',
    'enfoires.ballade': 'La Ballade des Enfoirés',
    'enfoires.countdown': 'Compte à rebours',
    'enfoires.days': 'Jours',
    'enfoires.hours': 'Heures',
    'enfoires.min': 'Min',
    'enfoires.sec': 'Sec',
    'enfoires.edition2026': 'Édition 2026',
    'enfoires.uniqueShow': 'Un spectacle unique de solidarité',
    'enfoires.showDesc': 'Le spectacle caritatif le plus populaire de France revient pour 7 soirées magiques à Paris-Bercy. Une édition exceptionnelle avec le retour de Florent Pagny et Bénabar !',
    'enfoires.contactUs': 'Contactez-nous',
    'enfoires.aboutText1': 'Du <strong>mardi 13 au lundi 19 janvier 2026</strong>, l\'Accor Arena de Paris-Bercy accueille la nouvelle édition des Enfoirés. Sept représentations exceptionnelles où les plus grands artistes français se réunissent pour <strong>lutter contre la faim et la précarité</strong>.',
    'enfoires.aboutText2': 'Cette édition promet des moments d\'émotion intense avec le <strong>retour très attendu de Florent Pagny</strong>, absent depuis 2021, et de <strong>Bénabar</strong> qui retrouve la troupe après quatre ans.',
    'enfoires.aboutText3': 'La troupe 2026 réserve également de belles surprises avec <strong>Héléna</strong> de la Star Academy, <strong>Pierre Garnier</strong>, <strong>Joseph Kamel</strong>, le virtuose <strong>Ibrahim Maalouf</strong>, l\'humoriste <strong>François-Xavier Demaison</strong> et le légendaire <strong>Alain Chamfort</strong>.',
    'enfoires.7dates': 'Les 7 dates du concert',
    'enfoires.january': 'Janvier',
    'enfoires.solidarity': 'Plus de 35 ans de solidarité',
    'enfoires.humanAdventure': 'Une aventure humaine et artistique unique',
    'enfoires.heritage': 'L\'héritage de Coluche',
    'enfoires.heritageDesc': 'Depuis 1989, Les Enfoirés perpétuent l\'esprit des Restos du Cœur fondés par Coluche en 1985. Les plus grands artistes français se mobilisent <strong>bénévolement</strong> pour offrir un spectacle mémorable au profit des plus démunis.',
    'enfoires.commitment': 'Un engagement sincère',
    'enfoires.commitmentDesc': '"Pas un seul artiste n\'a touché un centime pour sa participation", rappelle Bénabar. Chaque euro récolté finance des repas pour ceux qui en ont besoin. <strong>Les Enfoirés, c\'est sincère.</strong>',
    'enfoires.years': 'Années',
    'enfoires.mealsYear': 'Repas/an',
    'enfoires.artists': 'Artistes',
    'enfoires.exclusiveOffers': 'Nos offres exclusives',
    'enfoires.offersSubtitle': 'Offres réservées aux clients séjournant pendant Les Enfoirés',
    'enfoires.parking': 'Parking privé',
    'enfoires.parkingDesc': 'Stationnez en toute sécurité dans notre parking privé pendant votre séjour',
    'enfoires.parkingPrice': 'Seulement 15€ / jour',
    'enfoires.taxi': 'Taxi partenaire',
    'enfoires.taxiDesc': 'Réduction sur vos trajets pour vous rendre à l\'Accor Arena et en revenir',
    'enfoires.taxiDiscount': '-10%',
    'enfoires.offersNote': '* Ces offres sont valables uniquement lors de votre séjour pendant l\'événement',
    'enfoires.watchVideo': 'Découvrez Les Enfoirés en vidéo',
    'enfoires.specialOffer': 'Notre offre spéciale Enfoirés',
    'enfoires.bestConditions': 'Profitez du concert dans les meilleures conditions',
    'enfoires.bookNow': 'Réservez votre séjour maintenant',
    'enfoires.moreEvents': 'Découvrez nos autres événements',
    
    // Rugby Page
    'rugby.tournament': 'Tournoi des 6 Nations 2025',
    'rugby.title': 'France vs Irlande',
    'rugby.subtitle': 'Le choc au sommet du rugby européen au Stade de France',
    'rugby.unmissable': 'Un événement incontournable',
    'rugby.tournamentDesc': 'Organisé chaque année, le Tournoi des 6 Nations réunit les six grandes nations européennes du rugby : la <strong>France</strong>, l\'<strong>Angleterre</strong>, l\'<strong>Écosse</strong>, l\'<strong>Irlande</strong>, le <strong>Pays de Galles</strong> et l\'<strong>Italie</strong>.',
    'rugby.prestigeDesc': 'Cette compétition prestigieuse est l\'occasion de vivre des moments d\'intense émotion et de découvrir le meilleur du rugby européen dans une ambiance électrique.',
    'rugby.welcome': 'Supporters français et irlandais, notre hôtel vous accueille avec le même enthousiasme !',
    'rugby.easyAccess': 'Stade de France facilement accessible',
    'rugby.accessDesc': 'Depuis l\'Hotel Inn Paris, rejoignez le Stade de France en toute simplicité grâce au métro. Un trajet direct et rapide pour ne rien manquer du spectacle !',
    'rugby.line13': 'Ligne 13',
    'rugby.duration': '~35 min',
    'rugby.route': 'Place d\'Italie → Saint-Denis',
    'rugby.relive': 'Revivez le dernier France - Irlande',
    'rugby.highlights': 'Les meilleurs moments de la dernière confrontation entre ces deux équipes',
    'rugby.probableLineups': 'Compositions probables',
    'rugby.expectedLineups': 'Les XV de départ attendus pour cette rencontre',
    'rugby.france': 'France',
    'rugby.ireland': 'Irlande',
    'rugby.last10': 'Les 10 derniers France - Irlande',
    'rugby.history': 'Historique des confrontations récentes',
    'rugby.record': 'Bilan',
    'rugby.wins': 'victoires',
    'rugby.exclusiveOffers': 'Nos offres exclusives',
    'rugby.offersSubtitle': 'Offres réservées aux clients séjournant pendant le Tournoi des 6 Nations',
    'rugby.parking': 'Parking privé',
    'rugby.parkingDesc': 'Stationnez en toute sécurité dans notre parking privé pendant votre séjour',
    'rugby.parkingPrice': 'Seulement 15€ / jour',
    'rugby.taxi': 'Taxi partenaire',
    'rugby.taxiDesc': 'Réduction sur vos trajets pour vous rendre au Stade de France et en revenir',
    'rugby.taxiDiscount': '-10%',
    'rugby.offersNote': '* Ces offres sont valables uniquement lors de votre séjour pendant l\'événement',
    'rugby.discoverParis': 'Profitez aussi de Paris',
    'rugby.parisDesc': 'Entre deux matchs, découvrez les incontournables de la capitale',
    'rugby.specialOffer': 'Notre offre spéciale 6 Nations',
    'rugby.bestConditions': 'Profitez du match dans les meilleures conditions',
    'rugby.bookNow': 'Réservez votre séjour maintenant',
    'rugby.moreEvents': 'Découvrez nos autres événements',
    
    // Agriculture Page
    'agriculture.badge': 'Salon International de l\'Agriculture',
    'agriculture.title': 'Salon de l\'Agriculture 2025',
    'agriculture.biggestFarm': 'La plus grande ferme de France s\'installe à Paris',
    'agriculture.bookAccommodation': 'Réserver votre hébergement',
    'agriculture.unmissable': 'Un événement incontournable',
    'agriculture.desc1': 'Le <strong>Salon International de l\'Agriculture</strong> est un événement parisien bien connu de tous les Français. Chaque année, cette grande foire agricole réunit plus de <strong>600 000 visiteurs</strong> au Parc des Expositions de la Porte de Versailles.',
    'agriculture.desc2': 'L\'objectif du célèbre Salon est de <strong>valoriser les produits agricoles</strong> français et de faire découvrir au grand public des <strong>produits locaux</strong> et des <strong>animaux d\'élevage</strong>. Une immersion unique dans le monde agricole sous toutes ses facettes !',
    'agriculture.atmosphere': 'L\'ambiance du Salon',
    'agriculture.familyMoments': 'Des moments uniques à partager en famille',
    'agriculture.milkingRoom': 'La salle de traite',
    'agriculture.milkingDesc': 'Découvrez le quotidien des éleveurs',
    'agriculture.animalMeetings': 'Rencontres animales',
    'agriculture.animalDesc': 'Un moment magique pour les enfants',
    'agriculture.easyAccess': 'Accès facile depuis l\'Hotel Inn Paris',
    'agriculture.accessDesc': 'Rejoignez le Salon en toute simplicité grâce aux transports en commun',
    'agriculture.byMetro': 'En Métro',
    'agriculture.metroTime': '~25 minutes',
    'agriculture.metroRoute': '<strong>Ligne 7</strong> depuis Place d\'Italie jusqu\'à <strong>Porte de Versailles</strong> (correspondance ligne 12).',
    'agriculture.hours': 'Horaires du Salon',
    'agriculture.hoursTime': '9h - 19h',
    'agriculture.hoursDesc': 'Ouvert tous les jours de <strong>9h à 19h</strong>. Nocturne le vendredi jusqu\'à 23h.',
    'agriculture.location': 'Parc des Expositions',
    'agriculture.address': '<strong>1 Place de la Porte de Versailles</strong>, 75015 Paris',
    'agriculture.comfort': 'Votre confort après une journée au Salon',
    'agriculture.comfortDesc': 'Profitez d\'un hébergement de qualité pour vous ressourcer après avoir arpenté les allées du Salon',
    'agriculture.breakfast': 'Petit-déjeuner copieux',
    'agriculture.breakfastDesc': 'Buffet généreux avec produits frais pour bien commencer votre journée de visite',
    'agriculture.transport': 'Proximité transports',
    'agriculture.transportDesc': 'Métro à 2 minutes à pied pour rejoindre facilement la Porte de Versailles',
    'agriculture.rooms': 'Chambres confortables',
    'agriculture.roomsDesc': 'Reposez-vous dans nos chambres douillettes après une journée au Salon',
    'agriculture.exclusiveOffers': 'Nos offres exclusives',
    'agriculture.offersSubtitle': 'Offres réservées aux clients séjournant pendant le Salon de l\'Agriculture',
    'agriculture.parking': 'Parking privé',
    'agriculture.parkingDesc': 'Stationnez en toute sécurité dans notre parking privé pendant votre séjour',
    'agriculture.parkingPrice': 'Seulement 15€ / jour',
    'agriculture.taxi': 'Taxi partenaire',
    'agriculture.taxiDesc': 'Réduction sur vos trajets pour vous rendre au Salon et en revenir',
    'agriculture.taxiDiscount': '-10%',
    'agriculture.offersNote': '* Ces offres sont valables uniquement lors de votre séjour pendant l\'événement',
    'agriculture.otherSalons': 'Autres salons à Porte de Versailles',
    'agriculture.otherSalonsDesc': 'Découvrez les autres événements à venir',
    'agriculture.specialOffer': 'Notre offre spéciale Salon',
    'agriculture.bestConditions': 'Profitez du Salon dans les meilleures conditions',
    'agriculture.bookNow': 'Réservez votre séjour maintenant',
    'agriculture.moreEvents': 'Découvrez nos autres événements',
    
    // Room booking button
    'rooms.bookButton': 'Réserver',
    
    // Seminar quote button  
    'seminars.quoteButton': 'Demander un devis',
    
    // Services Section
    'services.badge': 'À votre service',
    'services.title': 'Tout pour votre confort',
    'services.reception.title': 'Accueil & Infos pratiques',
    'services.reception.247': 'Réception 24/24 – 7j/7',
    'services.reception.checkin': 'Départ avant 12h – Arrivée après 14h',
    'services.reception.parking': 'Parking privé et sécurisé',
    'services.reception.luggage': 'Bagagerie gratuite',
    'services.reception.taxi': 'Taxi – Tarif unique aéroport',
    'services.restaurant.title': 'Restaurant à proximité',
    'services.restaurant.desc': 'Que vous soyez à la recherche de plats locaux et traditionnels, de saveurs internationales exotiques ou de mets gastronomiques raffinés, il y a de fortes chances que vous puissiez trouver un restaurant adapté à vos envies.',
    'services.tourism.title': 'Tourisme',
    'services.tourism.desc': 'Lors de votre séjour à l\'hôtel Inn Design Place d\'Italie à Paris, vous pourrez vous plonger dans l\'histoire de la capitale française : Les Catacombes de Paris, La Tour Eiffel, Tour Montparnasse, Institut du monde arabe, Musée du Louvres, Panthéon...',
    
    // CTA
    'cta.badge': 'Meilleur Prix Garanti',
    'cta.title': 'Moins cher ici qu\'ailleurs, c\'est garanti',
    'cta.subtitle': 'Aucune plateforme ne battra notre prix !',
    'cta.description': 'Comparez par vous-même : vous ne trouverez jamais moins cher qu\'en réservant directement sur notre site. C\'est notre promesse.',
    'cta.button': 'Réserver au meilleur prix',
    'cta.contact': 'Nous contacter',
    'cta.moreExpensive': '+ Cher',
    'cta.noAdvantages': 'Aucun avantage',
    'cta.bestPrice': 'Meilleur tarif',
    'cta.ourSite': 'Site officiel',
    'cta.exclusiveAdvantages': 'avantages exclusifs',
    'cta.advantage1': '-15% garanti',
    'cta.advantage2': 'Avantages exclusifs',
    'cta.advantage3': 'Réservation sécurisée',
    
    // Contact Bubble
    'contact.bubble': 'Contactez-nous',
    
    // Footer
    'footer.description': 'Hôtel 3 étoiles au cœur du 13ème arrondissement, à deux pas de la Place d\'Italie.',
    'footer.navigation': 'Navigation',
    'footer.contact': 'Contact',
    'footer.rights': 'Tous droits réservés.',
    'footer.legal': 'Mentions légales',
    'footer.privacy': 'Politique de confidentialité',
  },
  en: {
    // Navigation
    'nav.hotel': 'The Hotel',
    'nav.home': 'Home',
    'nav.rooms': 'Our Rooms',
    'nav.breakfast': 'Breakfast',
    'nav.seminars': 'Seminars',
    'nav.location': 'Location',
    'nav.events': 'Events',
    'nav.contact': 'Contact',
    'nav.book': 'Book',
    
    // Hero
    'hero.welcome': 'Welcome',
    'hero.name': 'Hotel Inn Design',
    'hero.location': "Place d'Italie",
    
    // Intro
    'intro.badge': 'Welcome',
    'intro.title': 'A well-located hotel for everything!',
    'intro.description': "Located in the heart of the 13th arrondissement, Hotel Inn Design Paris enjoys an ideal location, close to Butte-aux-Cailles, parks and the quays. Our hotel offers 70 comfortable rooms, a private and secure car park, as well as a friendly bar and a reception area conducive to relaxation or professional exchanges.",
    'intro.cta': 'Book your room and enjoy your stay in Paris!',
    'intro.button': 'Book a room',
    'intro.stars': '3 stars',
    'intro.rooms': '70 rooms',
    'intro.parking': 'Private parking',
    'intro.bar': 'Friendly bar',
    
    // Rooms Section
    'rooms.badge': 'Our Accommodations',
    'rooms.title': 'Rooms & Suites',
    'rooms.subtitle': 'Unpack and enjoy!',
    'rooms.description': 'Settle into one of our 70 bright, soundproofed and fully equipped rooms for your comfort.',
    'rooms.description2': 'Air conditioning, flat-screen TV, desk area, safe, hairdryer, courtesy tray... everything is designed for you.',
    'rooms.viewAll': 'See all our rooms',
    'rooms.book': 'Book a room',
    'rooms.double': 'Double Room',
    'rooms.double.desc': '160×200 cm bed. Enjoy an elegant and comfortable space, ideal for a couple or solo stay.',
    'rooms.twin': 'Twin Room',
    'rooms.twin.desc': '2 beds of 100×200 cm. Perfect for trips with friends or colleagues, with all the necessary comfort.',
    'rooms.superior': 'Superior Room with balcony',
    'rooms.superior.desc': 'Enjoy a private outdoor space with views of Paris. A unique experience in the heart of the city.',
    'rooms.connecting': 'Connecting Rooms',
    'rooms.connecting.desc': '2 modular rooms with connecting doors. The ideal solution for families or groups.',
    'rooms.bathroom': 'Private bathroom',
    'rooms.tv': 'Flat screen TV',
    'rooms.desk': 'Desk area',
    'rooms.wifi': 'Free Wi-Fi',
    'rooms.courtesy': 'Courtesy tray',
    'rooms.ac': 'Air conditioning',
    
    // Rooms Page
    'roomsPage.badge': 'Our Accommodations',
    'roomsPage.title': 'The rooms of Hotel Inn Design Paris',
    'roomsPage.intro': 'Enjoy 70 bright, soundproofed and comfortable rooms, with equipped bathroom. Solo, with family or friends, everything is designed for your well-being, with connecting rooms and a caring team. Ideally located, the hotel is the perfect starting point to discover Paris stress-free.',
    'roomsPage.ourRooms': 'Our accommodations',
    'roomsPage.discover': 'Discover our rooms',
    'roomsPage.gallery': 'Photo Gallery',
    'roomsPage.spaces': 'Discover our spaces',
    'roomsPage.view': 'View',
    'roomsPage.cta.title': 'Book your room now',
    'roomsPage.cta.subtitle': 'Get -15% by booking directly on our website',
    'roomsPage.cta.button': 'Check availability',
    'roomsPage.double.name': 'Double Room',
    'roomsPage.double.details': '160×200 cm bed',
    'roomsPage.double.desc': 'Enjoy an elegant and comfortable space, ideal for a couple or solo stay. Equipped with all modern comforts, this room offers you a haven of peace in the heart of Paris.',
    'roomsPage.twin.name': 'Twin Room',
    'roomsPage.twin.details': '2 beds of 100×200 cm',
    'roomsPage.twin.desc': 'Perfect for trips with friends or colleagues, with all the necessary comfort. Two separate beds in an optimized space for a pleasant stay.',
    'roomsPage.superior.name': 'Superior Room with Balcony',
    'roomsPage.superior.details': 'Paris view',
    'roomsPage.superior.desc': 'Enjoy a private outdoor space with views of Paris. A unique experience in the heart of the city. Ideal for enjoying your breakfast while admiring the Parisian rooftops.',
    'roomsPage.connecting.name': 'Connecting Rooms',
    'roomsPage.connecting.details': '2 modular rooms',
    'roomsPage.connecting.desc': 'Two rooms with connecting doors, the ideal solution for families or groups. Enjoy the privacy of separate rooms while staying connected.',
    
    // About / Location
    'about.badge': 'Ideal location',
    'about.title': 'A hotel in the heart of Paris',
    'about.description': 'Hotel Inn Paris is located 2 minutes walk from the Parisian metro and offers great convenience.',
    'about.metro': 'Metro access (exit 3)',
    
    // Location Section (Homepage)
    'location.badge': 'How to find us',
    'location.title': 'Location',
    'location.access': 'Access',
    'location.metro': 'Metro',
    'location.bus': 'Bus',
    'location.tramway': 'Tramway',
    'location.parking': 'Private secure parking available upon reservation.',
    
    // Location Page
    'locationPage.badge': 'Find us',
    'locationPage.title': 'Our location',
    'locationPage.openMaps': 'Open in Google Maps',
    'locationPage.idealLocation': 'Ideally located',
    'locationPage.heartOfParis': 'A hotel in the heart of Paris',
    'locationPage.heartDesc': 'Steps from the Place d\'Italie metro, enjoy quick access to all the capital\'s monuments and attractions.',
    'locationPage.parking': 'Parking',
    'locationPage.parkingDesc': 'Private secure parking (€15/day)',
    'locationPage.reception': 'Reception',
    'locationPage.receptionDesc': 'Open 24/7',
    'locationPage.needDirections': 'Need directions?',
    'locationPage.airport.cdg': 'Paris-CDG Airport',
    'locationPage.airport.orly': 'Paris-Orly Airport',
    'locationPage.eiffel': 'Eiffel Tower',
    'locationPage.louvre': 'Louvre Museum',
    'locationPage.champs': 'Champs-Élysées',
    'locationPage.pantheon': 'The Pantheon',
    
    // Breakfast
    'breakfast.badge': 'At your service',
    'breakfast.title': 'Breakfast & Bar',
    'breakfast.subtitle': 'The breakfast that makes you smile!',
    'breakfast.desc1': 'Every morning, fill up on energy with our full breakfast, served as an all-you-can-eat sweet & savory buffet.',
    'breakfast.desc2': 'On the menu: hot drinks, traditional baguettes and cereals, crispy pastries, fresh fruits and cereals. On the savory side, find hard-boiled eggs, cold cuts, turkey breast, cheeses and organic plain yogurts. And for those with a sweet tooth: jams and delicate vanilla pancakes.',
    'breakfast.cta': 'Discover our breakfast',
    'breakfast.bar.title': 'A friendly bar to relax',
    'breakfast.bar.desc1': 'At any time of the day, settle in at the hotel bar to share a drink, chat or simply take a break.',
    'breakfast.bar.desc2': 'In a welcoming and relaxed atmosphere, it\'s the ideal place to meet up after a busy day.',
    
    // Breakfast Page
    'breakfastPage.badge': 'Every morning',
    'breakfastPage.title': 'The breakfast that makes you smile!',
    'breakfastPage.intro1': 'Every morning, fill up on energy with our full breakfast, served as an all-you-can-eat sweet & savory buffet.',
    'breakfastPage.intro2': 'On the menu: hot drinks, traditional baguettes and cereals, crispy pastries, fresh fruits and cereals. On the savory side, find hard-boiled eggs, cold cuts, turkey breast, cheeses and organic plain yogurts. And for those with a sweet tooth: jams and delicate vanilla pancakes.',
    'breakfastPage.enjoy': 'Everything you need to start the day right, whatever your plans!',
    'breakfastPage.hours': 'Hours',
    'breakfastPage.hoursValue': '7:00 AM - 10:00 AM',
    'breakfastPage.formula': 'Formula',
    'breakfastPage.formulaValue': 'All-you-can-eat buffet',
    'breakfastPage.hotDrinks': 'Hot drinks',
    'breakfastPage.pastries': 'Pastries',
    'breakfastPage.fruits': 'Fresh fruits',
    'breakfastPage.savory': 'Savory buffet',
    'breakfastPage.gallery': 'Photo Gallery',
    'breakfastPage.space': 'Our breakfast area',
    'breakfastPage.view': 'View',
    
    // Seminars
    'seminars.badge': 'Professional space',
    'seminars.title': 'Seminar room',
    'seminars.subtitle': 'Organize your meetings differently!',
    'seminars.desc1': 'Hotel Inn Design Paris provides you with several modern and fully equipped seminar rooms: flipchart, screens with video projector, microphones and wifi connection.',
    'seminars.desc2': 'Depending on your objectives, different configurations are possible to perfectly adapt to your meetings, training sessions or professional events.',
    'seminars.quote': 'Request a quote',
    'seminars.discover': 'Discover our rooms',
    
    // Seminars Page
    'seminarsPage.badge': 'Seminars & Events',
    'seminarsPage.title': 'Our seminar rooms',
    'seminarsPage.intro1': 'Organize your meetings, training sessions or professional events in our modern and modular rooms, perfect for small teams or large delegations.',
    'seminarsPage.intro2': 'After a productive day, your participants can enjoy comfortable rooms and relaxation areas.',
    'seminarsPage.intro3': 'We also offer modular lounges for your cocktails, banquets or study days, all in a practical and pleasant setting.',
    'seminarsPage.equipment': 'Equipment included',
    'seminarsPage.projector': 'Video projector',
    'seminarsPage.screen': 'Projection screen',
    'seminarsPage.wifi': 'High-speed Wi-Fi',
    'seminarsPage.coffee': 'Coffee breaks',
    'seminarsPage.modular': 'Modular configurations',
    'seminarsPage.catering': 'Catering service',
    'seminarsPage.spaces': 'Our spaces',
    'seminarsPage.meetingRooms': 'Meeting rooms',
    'seminarsPage.virtualTour': 'Virtual Tour',
    'seminarsPage.videoTitle': 'Discover our spaces on video',
    'seminarsPage.cta.title': 'Request a personalized quote',
    'seminarsPage.cta.subtitle': 'Our team supports you in organizing your event',
    'seminarsPage.cta.button': 'Contact us',
    'seminarsPage.uShape': 'U-shape',
    'seminarsPage.classroom': 'Classroom',
    'seminarsPage.theatre': 'Theatre',
    
    // Events
    'events.badge': 'Events & Offers',
    'events.title': 'Discover our agenda and offers',
    'events.cta': 'See all events',
    
    // Actualites Page
    'actualites.hero.badge': 'Events & Offers',
    'actualites.hero.title': 'Our events and exclusive offers',
    'actualites.hero.description': 'Discover upcoming events, concerts, promotions and special offers at Hotel Inn Design Paris.',
    'actualites.readTime': 'read',
    'actualites.learnMore': 'Learn more',
    'actualites.allEvents': 'All events',
    'actualites.loadMore': 'See more events',
    'actualites.newsletter.title': 'Stay informed',
    'actualites.newsletter.description': 'Subscribe to our newsletter to receive our latest news and exclusive offers.',
    'actualites.newsletter.placeholder': 'Your email',
    'actualites.newsletter.button': 'Subscribe',
    
    // Room booking button
    'rooms.bookButton': 'Book',
    
    // Seminar quote button
    'seminars.quoteButton': 'Request a quote',
    
    // Services Section
    'services.badge': 'At your service',
    'services.title': 'Everything for your comfort',
    'services.reception.title': 'Reception & Practical info',
    'services.reception.247': 'Reception 24/7',
    'services.reception.checkin': 'Check-out before 12pm – Check-in after 2pm',
    'services.reception.parking': 'Private secure parking',
    'services.reception.luggage': 'Free luggage storage',
    'services.reception.taxi': 'Taxi – Fixed airport rate',
    'services.restaurant.title': 'Nearby restaurants',
    'services.restaurant.desc': 'Whether you\'re looking for local and traditional dishes, exotic international flavors or refined gourmet cuisine, chances are you can find a restaurant that suits your cravings.',
    'services.tourism.title': 'Tourism',
    'services.tourism.desc': 'During your stay at Hotel Inn Design Place d\'Italie in Paris, you can immerse yourself in the history of the French capital: The Catacombs of Paris, The Eiffel Tower, Montparnasse Tower, Arab World Institute, Louvre Museum, Pantheon...',
    
    // CTA
    'cta.badge': 'Best Price Guaranteed',
    'cta.title': 'Cheaper here than anywhere else, guaranteed',
    'cta.subtitle': 'No platform will beat our price!',
    'cta.description': 'Compare for yourself: you will never find a cheaper rate than booking directly on our website. That\'s our promise.',
    'cta.button': 'Book at the best price',
    'cta.contact': 'Contact us',
    'cta.moreExpensive': 'More $',
    'cta.noAdvantages': 'No perks',
    'cta.bestPrice': 'Best rate',
    'cta.ourSite': 'Official website',
    'cta.exclusiveAdvantages': 'exclusive perks',
    'cta.advantage1': '-15% guaranteed',
    'cta.advantage2': 'Exclusive perks',
    'cta.advantage3': 'Secure booking',
    
    // Contact Bubble
    'contact.bubble': 'Contact us',
    
    // Footer
    'footer.description': '3-star hotel in the heart of the 13th arrondissement, steps from Place d\'Italie.',
    'footer.navigation': 'Navigation',
    'footer.contact': 'Contact',
    'footer.rights': 'All rights reserved.',
    'footer.legal': 'Legal notice',
    'footer.privacy': 'Privacy policy',
  },
  es: {
    // Navigation
    'nav.hotel': 'El Hotel',
    'nav.home': 'Inicio',
    'nav.rooms': 'Habitaciones',
    'nav.breakfast': 'Desayuno',
    'nav.seminars': 'Seminarios',
    'nav.location': 'Ubicación',
    'nav.events': 'Eventos',
    'nav.contact': 'Contacto',
    'nav.book': 'Reservar',
    
    // Hero
    'hero.welcome': 'Bienvenido',
    'hero.name': 'Hotel Inn Design',
    'hero.location': "Place d'Italie",
    
    // Intro
    'intro.badge': 'Bienvenido',
    'intro.title': '¡Un hotel bien ubicado para todo!',
    'intro.description': "Situado en el corazón del distrito 13, Hotel Inn Design París disfruta de una ubicación ideal, cerca de Butte-aux-Cailles, parques y muelles. Nuestro hotel ofrece 70 habitaciones confortables, un aparcamiento privado y seguro, así como un bar acogedor y una zona de recepción propicia para el relax o los intercambios profesionales.",
    'intro.cta': '¡Reserve su habitación y disfrute de su estancia en París!',
    'intro.button': 'Reservar habitación',
    'intro.stars': '3 estrellas',
    'intro.rooms': '70 habitaciones',
    'intro.parking': 'Parking privado',
    'intro.bar': 'Bar acogedor',
    
    // Rooms Section
    'rooms.badge': 'Alojamientos',
    'rooms.title': 'Habitaciones & Suites',
    'rooms.subtitle': '¡Desempaque y disfrute!',
    'rooms.description': 'Instálese en una de nuestras 70 habitaciones luminosas, insonorizadas y totalmente equipadas para su comodidad.',
    'rooms.description2': 'Aire acondicionado, TV de pantalla plana, escritorio, caja fuerte, secador de pelo, bandeja de cortesía... todo está pensado para usted.',
    'rooms.viewAll': 'Ver todas las habitaciones',
    'rooms.book': 'Reservar habitación',
    'rooms.double': 'Habitación Doble',
    'rooms.double.desc': 'Cama de 160×200 cm. Disfrute de un espacio elegante y confortable, ideal para parejas o estancias en solitario.',
    'rooms.twin': 'Habitación Twin',
    'rooms.twin.desc': '2 camas de 100×200 cm. Perfecta para viajes con amigos o colegas, con todo el confort necesario.',
    'rooms.superior': 'Habitación Superior con balcón',
    'rooms.superior.desc': 'Disfrute de un espacio exterior privado con vistas a París. Una experiencia única en el corazón de la ciudad.',
    'rooms.connecting': 'Habitaciones Comunicantes',
    'rooms.connecting.desc': '2 habitaciones modulables con puertas comunicantes. La solución ideal para familias o grupos.',
    'rooms.bathroom': 'Baño privado',
    'rooms.tv': 'TV pantalla plana',
    'rooms.desk': 'Escritorio',
    'rooms.wifi': 'Wi-Fi gratis',
    'rooms.courtesy': 'Bandeja de cortesía',
    'rooms.ac': 'Aire acondicionado',
    
    // Rooms Page
    'roomsPage.badge': 'Nuestros Alojamientos',
    'roomsPage.title': 'Las habitaciones del Hotel Inn Design París',
    'roomsPage.intro': 'Disfrute de 70 habitaciones luminosas, insonorizadas y confortables, con baño equipado. Solo, en familia o con amigos, todo está pensado para su bienestar, con habitaciones comunicantes y un equipo atento. Idealmente ubicado, el hotel es el punto de partida perfecto para descubrir París sin estrés.',
    'roomsPage.ourRooms': 'Nuestros alojamientos',
    'roomsPage.discover': 'Descubra nuestras habitaciones',
    'roomsPage.gallery': 'Galería de Fotos',
    'roomsPage.spaces': 'Descubra nuestros espacios',
    'roomsPage.view': 'Ver',
    'roomsPage.cta.title': 'Reserve su habitación ahora',
    'roomsPage.cta.subtitle': 'Obtenga -15% reservando directamente en nuestro sitio',
    'roomsPage.cta.button': 'Ver disponibilidad',
    'roomsPage.double.name': 'Habitación Doble',
    'roomsPage.double.details': 'Cama de 160×200 cm',
    'roomsPage.double.desc': 'Disfrute de un espacio elegante y confortable, ideal para parejas o estancias en solitario. Equipada con todo el confort moderno, esta habitación le ofrece un remanso de paz en el corazón de París.',
    'roomsPage.twin.name': 'Habitación Twin',
    'roomsPage.twin.details': '2 camas de 100×200 cm',
    'roomsPage.twin.desc': 'Perfecta para viajes con amigos o colegas, con todo el confort necesario. Dos camas separadas en un espacio optimizado para una estancia agradable.',
    'roomsPage.superior.name': 'Habitación Superior con Balcón',
    'roomsPage.superior.details': 'Vista a París',
    'roomsPage.superior.desc': 'Disfrute de un espacio exterior privado con vistas a París. Una experiencia única en el corazón de la ciudad. Ideal para disfrutar del desayuno admirando los tejados parisinos.',
    'roomsPage.connecting.name': 'Habitaciones Comunicantes',
    'roomsPage.connecting.details': '2 habitaciones modulables',
    'roomsPage.connecting.desc': 'Dos habitaciones con puertas comunicantes, la solución ideal para familias o grupos. Disfrute de la privacidad de habitaciones separadas manteniéndose conectados.',
    
    // About / Location
    'about.badge': 'Ubicación ideal',
    'about.title': 'Un hotel en el corazón de París',
    'about.description': 'Hotel Inn París está a 2 minutos a pie del metro parisino y ofrece gran comodidad.',
    'about.metro': 'Acceso metro (salida 3)',
    
    // Location Section (Homepage)
    'location.badge': 'Cómo encontrarnos',
    'location.title': 'Ubicación',
    'location.access': 'Acceso',
    'location.metro': 'Metro',
    'location.bus': 'Autobús',
    'location.tramway': 'Tranvía',
    'location.parking': 'Parking privado seguro disponible con reserva.',
    
    // Location Page
    'locationPage.badge': 'Encuéntrenos',
    'locationPage.title': 'Nuestra ubicación',
    'locationPage.openMaps': 'Abrir en Google Maps',
    'locationPage.idealLocation': 'Idealmente ubicado',
    'locationPage.heartOfParis': 'Un hotel en el corazón de París',
    'locationPage.heartDesc': 'A pasos del metro Place d\'Italie, disfrute de acceso rápido a todos los monumentos y atracciones de la capital.',
    'locationPage.parking': 'Parking',
    'locationPage.parkingDesc': 'Parking privado seguro (15€/día)',
    'locationPage.reception': 'Recepción',
    'locationPage.receptionDesc': 'Abierta 24/7',
    'locationPage.needDirections': '¿Necesita indicaciones?',
    'locationPage.airport.cdg': 'Aeropuerto París-CDG',
    'locationPage.airport.orly': 'Aeropuerto París-Orly',
    'locationPage.eiffel': 'Torre Eiffel',
    'locationPage.louvre': 'Museo del Louvre',
    'locationPage.champs': 'Campos Elíseos',
    'locationPage.pantheon': 'El Panteón',
    
    // Breakfast
    'breakfast.badge': 'A su servicio',
    'breakfast.title': 'Desayuno & Bar',
    'breakfast.subtitle': '¡El desayuno que te hace sonreír!',
    'breakfast.desc1': 'Cada mañana, llénese de energía con nuestro desayuno completo, servido en buffet dulce y salado a voluntad.',
    'breakfast.desc2': 'En el menú: bebidas calientes, baguettes tradicionales y cereales, bollería crujiente, frutas frescas y cereales. En el lado salado, huevos duros, embutidos, pechuga de pavo, quesos y yogures naturales bio. Y para los más golosos: mermeladas y crepes suaves delicadamente vainilladas.',
    'breakfast.cta': 'Descubrir nuestro desayuno',
    'breakfast.bar.title': 'Un bar acogedor para relajarse',
    'breakfast.bar.desc1': 'En cualquier momento del día, siéntese en el bar del hotel para compartir una copa, charlar o simplemente hacer una pausa.',
    'breakfast.bar.desc2': 'En un ambiente acogedor y relajado, es el lugar ideal para reunirse después de un día ajetreado.',
    
    // Breakfast Page
    'breakfastPage.badge': 'Cada mañana',
    'breakfastPage.title': '¡El desayuno que te hace sonreír!',
    'breakfastPage.intro1': 'Cada mañana, llénese de energía con nuestro desayuno completo, servido en buffet dulce y salado a voluntad.',
    'breakfastPage.intro2': 'En el menú: bebidas calientes, baguettes tradicionales y cereales, bollería crujiente, frutas frescas y cereales. En el lado salado, huevos duros, embutidos, pechuga de pavo, quesos y yogures naturales bio. Y para los más golosos: mermeladas y crepes suaves delicadamente vainilladas.',
    'breakfastPage.enjoy': '¡Todo lo necesario para empezar bien el día, sea cual sea su programa!',
    'breakfastPage.hours': 'Horarios',
    'breakfastPage.hoursValue': '7:00 - 10:00',
    'breakfastPage.formula': 'Fórmula',
    'breakfastPage.formulaValue': 'Buffet libre',
    'breakfastPage.hotDrinks': 'Bebidas calientes',
    'breakfastPage.pastries': 'Bollería',
    'breakfastPage.fruits': 'Frutas frescas',
    'breakfastPage.savory': 'Buffet salado',
    'breakfastPage.gallery': 'Galería de Fotos',
    'breakfastPage.space': 'Nuestra zona de desayuno',
    'breakfastPage.view': 'Ver',
    
    // Seminars
    'seminars.badge': 'Espacio profesional',
    'seminars.title': 'Sala de seminarios',
    'seminars.subtitle': '¡Organice sus reuniones de otra manera!',
    'seminars.desc1': 'Hotel Inn Design París pone a su disposición varias salas de seminarios modernas y totalmente equipadas: rotafolio, pantallas con videoproyector, micrófonos y conexión wifi.',
    'seminars.desc2': 'Según sus objetivos, diferentes configuraciones son posibles para adaptarse perfectamente a sus reuniones, formaciones o eventos profesionales.',
    'seminars.quote': 'Solicitar presupuesto',
    'seminars.discover': 'Descubrir nuestras salas',
    
    // Seminars Page
    'seminarsPage.badge': 'Seminarios y Eventos',
    'seminarsPage.title': 'Nuestras salas de seminarios',
    'seminarsPage.intro1': 'Organice sus reuniones, formaciones o eventos profesionales en nuestras salas modernas y modulables, perfectas para equipos pequeños o grandes delegaciones.',
    'seminarsPage.intro2': 'Después de un día productivo, sus participantes podrán disfrutar de habitaciones confortables y zonas de descanso.',
    'seminarsPage.intro3': 'También ofrecemos salones modulables para sus cócteles, banquetes o jornadas de estudio, todo en un entorno práctico y agradable.',
    'seminarsPage.equipment': 'Equipamiento incluido',
    'seminarsPage.projector': 'Videoproyector',
    'seminarsPage.screen': 'Pantalla de proyección',
    'seminarsPage.wifi': 'Wi-Fi de alta velocidad',
    'seminarsPage.coffee': 'Pausas café',
    'seminarsPage.modular': 'Configuraciones modulables',
    'seminarsPage.catering': 'Servicio de catering',
    'seminarsPage.spaces': 'Nuestros espacios',
    'seminarsPage.meetingRooms': 'Salas de reuniones',
    'seminarsPage.virtualTour': 'Visita Virtual',
    'seminarsPage.videoTitle': 'Descubra nuestros espacios en vídeo',
    'seminarsPage.cta.title': 'Solicite un presupuesto personalizado',
    'seminarsPage.cta.subtitle': 'Nuestro equipo le acompaña en la organización de su evento',
    'seminarsPage.cta.button': 'Contáctenos',
    'seminarsPage.uShape': 'En U',
    'seminarsPage.classroom': 'Clase',
    'seminarsPage.theatre': 'Teatro',
    
    // Events
    'events.badge': 'Eventos y Ofertas',
    'events.title': 'Descubra nuestra agenda y ofertas',
    'events.cta': 'Ver todos los eventos',
    
    // Actualites Page
    'actualites.hero.badge': 'Eventos y Ofertas',
    'actualites.hero.title': 'Nuestros eventos y ofertas exclusivas',
    'actualites.hero.description': 'Descubra los próximos eventos, conciertos, promociones y ofertas especiales del Hotel Inn Design París.',
    'actualites.readTime': 'de lectura',
    'actualites.learnMore': 'Saber más',
    'actualites.allEvents': 'Todos los eventos',
    'actualites.loadMore': 'Ver más eventos',
    'actualites.newsletter.title': 'Manténgase informado',
    'actualites.newsletter.description': 'Suscríbase a nuestro boletín para recibir nuestras últimas noticias y ofertas exclusivas.',
    'actualites.newsletter.placeholder': 'Su email',
    'actualites.newsletter.button': 'Suscribirse',
    
    // Room booking button
    'rooms.bookButton': 'Reservar',
    
    // Seminar quote button
    'seminars.quoteButton': 'Solicitar presupuesto',
    
    // Services Section
    'services.badge': 'A su servicio',
    'services.title': 'Todo para su comodidad',
    'services.reception.title': 'Recepción e Información práctica',
    'services.reception.247': 'Recepción 24/7',
    'services.reception.checkin': 'Salida antes de las 12h – Llegada después de las 14h',
    'services.reception.parking': 'Parking privado y seguro',
    'services.reception.luggage': 'Consigna gratuita',
    'services.reception.taxi': 'Taxi – Tarifa única aeropuerto',
    'services.restaurant.title': 'Restaurantes cercanos',
    'services.restaurant.desc': 'Ya sea que busque platos locales y tradicionales, sabores internacionales exóticos o cocina gourmet refinada, es muy probable que encuentre un restaurante adaptado a sus deseos.',
    'services.tourism.title': 'Turismo',
    'services.tourism.desc': 'Durante su estancia en el Hotel Inn Design Place d\'Italie en París, podrá sumergirse en la historia de la capital francesa: Las Catacumbas de París, La Torre Eiffel, Torre Montparnasse, Instituto del Mundo Árabe, Museo del Louvre, Panteón...',
    
    // CTA
    'cta.badge': 'Mejor Precio Garantizado',
    'cta.title': 'Más barato aquí que en cualquier otro lugar',
    'cta.subtitle': '¡Ninguna plataforma superará nuestro precio!',
    'cta.description': 'Compárelo usted mismo: nunca encontrará un precio más bajo que reservando directamente en nuestro sitio. Es nuestra promesa.',
    'cta.button': 'Reservar al mejor precio',
    'cta.contact': 'Contáctenos',
    'cta.moreExpensive': 'Más caro',
    'cta.noAdvantages': 'Sin ventajas',
    'cta.bestPrice': 'Mejor tarifa',
    'cta.ourSite': 'Sitio oficial',
    'cta.exclusiveAdvantages': 'ventajas exclusivas',
    'cta.advantage1': '-15% garantizado',
    'cta.advantage2': 'Ventajas exclusivas',
    'cta.advantage3': 'Reserva segura',
    
    // Contact Bubble
    'contact.bubble': 'Contáctenos',
    
    // Footer
    'footer.description': 'Hotel de 3 estrellas en el corazón del distrito 13, a pasos de Place d\'Italie.',
    'footer.navigation': 'Navegación',
    'footer.contact': 'Contacto',
    'footer.rights': 'Todos los derechos reservados.',
    'footer.legal': 'Aviso legal',
    'footer.privacy': 'Política de privacidad',
  },
  it: {
    // Navigation
    'nav.hotel': "L'Hotel",
    'nav.home': 'Home',
    'nav.rooms': 'Camere',
    'nav.breakfast': 'Colazione',
    'nav.seminars': 'Seminari',
    'nav.location': 'Posizione',
    'nav.events': 'Eventi',
    'nav.contact': 'Contatto',
    'nav.book': 'Prenota',
    
    // Hero
    'hero.welcome': 'Benvenuto',
    'hero.name': 'Hotel Inn Design',
    'hero.location': "Place d'Italie",
    
    // Intro
    'intro.badge': 'Benvenuto',
    'intro.title': 'Un hotel ben posizionato per tutto!',
    'intro.description': "Situato nel cuore del 13° arrondissement, l'Hotel Inn Design Paris gode di una posizione ideale, vicino a Butte-aux-Cailles, parchi e banchine. Il nostro hotel offre 70 camere confortevoli, un parcheggio privato e sicuro, nonché un bar accogliente e un'area reception propizia al relax o agli scambi professionali.",
    'intro.cta': 'Prenota la tua camera e goditi il tuo soggiorno a Parigi!',
    'intro.button': 'Prenota una camera',
    'intro.stars': '3 stelle',
    'intro.rooms': '70 camere',
    'intro.parking': 'Parcheggio privato',
    'intro.bar': 'Bar accogliente',
    
    // Rooms Section
    'rooms.badge': 'I nostri alloggi',
    'rooms.title': 'Camere & Suite',
    'rooms.subtitle': 'Disfa le valigie e goditi!',
    'rooms.description': 'Sistemati in una delle nostre 70 camere luminose, insonorizzate e completamente attrezzate per il tuo comfort.',
    'rooms.description2': 'Aria condizionata, TV a schermo piatto, scrivania, cassaforte, asciugacapelli, vassoio di cortesia... tutto è pensato per te.',
    'rooms.viewAll': 'Vedi tutte le camere',
    'rooms.book': 'Prenota una camera',
    'rooms.double': 'Camera Doppia',
    'rooms.double.desc': 'Letto 160×200 cm. Goditi uno spazio elegante e confortevole, ideale per un soggiorno di coppia o in solitaria.',
    'rooms.twin': 'Camera Twin',
    'rooms.twin.desc': '2 letti da 100×200 cm. Perfetta per viaggi con amici o colleghi, con tutto il comfort necessario.',
    'rooms.superior': 'Camera Superior con balcone',
    'rooms.superior.desc': 'Goditi uno spazio esterno privato con vista su Parigi. Un\'esperienza unica nel cuore della città.',
    'rooms.connecting': 'Camere Comunicanti',
    'rooms.connecting.desc': '2 camere modulabili con porte comunicanti. La soluzione ideale per famiglie o gruppi.',
    'rooms.bathroom': 'Bagno privato',
    'rooms.tv': 'TV schermo piatto',
    'rooms.desk': 'Scrivania',
    'rooms.wifi': 'Wi-Fi gratuito',
    'rooms.courtesy': 'Vassoio di cortesia',
    'rooms.ac': 'Aria condizionata',
    
    // Rooms Page
    'roomsPage.badge': 'I Nostri Alloggi',
    'roomsPage.title': 'Le camere dell\'Hotel Inn Design Paris',
    'roomsPage.intro': 'Goditi 70 camere luminose, insonorizzate e confortevoli, con bagno attrezzato. Da solo, in famiglia o con amici, tutto è pensato per il tuo benessere, con camere comunicanti e un team premuroso. Posizione ideale, l\'hotel è il punto di partenza perfetto per scoprire Parigi senza stress.',
    'roomsPage.ourRooms': 'I nostri alloggi',
    'roomsPage.discover': 'Scopri le nostre camere',
    'roomsPage.gallery': 'Galleria Foto',
    'roomsPage.spaces': 'Scopri i nostri spazi',
    'roomsPage.view': 'Vedi',
    'roomsPage.cta.title': 'Prenota la tua camera ora',
    'roomsPage.cta.subtitle': 'Ottieni -15% prenotando direttamente sul nostro sito',
    'roomsPage.cta.button': 'Verifica disponibilità',
    'roomsPage.double.name': 'Camera Doppia',
    'roomsPage.double.details': 'Letto 160×200 cm',
    'roomsPage.double.desc': 'Goditi uno spazio elegante e confortevole, ideale per un soggiorno di coppia o in solitaria. Dotata di tutti i comfort moderni, questa camera ti offre un\'oasi di pace nel cuore di Parigi.',
    'roomsPage.twin.name': 'Camera Twin',
    'roomsPage.twin.details': '2 letti da 100×200 cm',
    'roomsPage.twin.desc': 'Perfetta per viaggi con amici o colleghi, con tutto il comfort necessario. Due letti separati in uno spazio ottimizzato per un soggiorno piacevole.',
    'roomsPage.superior.name': 'Camera Superior con Balcone',
    'roomsPage.superior.details': 'Vista su Parigi',
    'roomsPage.superior.desc': 'Goditi uno spazio esterno privato con vista su Parigi. Un\'esperienza unica nel cuore della città. Ideale per gustare la colazione ammirando i tetti parigini.',
    'roomsPage.connecting.name': 'Camere Comunicanti',
    'roomsPage.connecting.details': '2 camere modulabili',
    'roomsPage.connecting.desc': 'Due camere con porte comunicanti, la soluzione ideale per famiglie o gruppi. Goditi la privacy di camere separate restando connessi.',
    
    // About / Location
    'about.badge': 'Posizione ideale',
    'about.title': 'Un hotel nel cuore di Parigi',
    'about.description': "L'Hotel Inn Paris si trova a 2 minuti a piedi dalla metropolitana parigina e offre grande comodità.",
    'about.metro': 'Accesso metro (uscita 3)',
    
    // Location Section (Homepage)
    'location.badge': 'Come trovarci',
    'location.title': 'Posizione',
    'location.access': 'Accesso',
    'location.metro': 'Metro',
    'location.bus': 'Autobus',
    'location.tramway': 'Tram',
    'location.parking': 'Parcheggio privato sicuro disponibile su prenotazione.',
    
    // Location Page
    'locationPage.badge': 'Trovaci',
    'locationPage.title': 'La nostra posizione',
    'locationPage.openMaps': 'Apri in Google Maps',
    'locationPage.idealLocation': 'Posizione ideale',
    'locationPage.heartOfParis': 'Un hotel nel cuore di Parigi',
    'locationPage.heartDesc': 'A due passi dalla metro Place d\'Italie, goditi un accesso rapido a tutti i monumenti e le attrazioni della capitale.',
    'locationPage.parking': 'Parcheggio',
    'locationPage.parkingDesc': 'Parcheggio privato sicuro (15€/giorno)',
    'locationPage.reception': 'Reception',
    'locationPage.receptionDesc': 'Aperta 24/7',
    'locationPage.needDirections': 'Hai bisogno di indicazioni?',
    'locationPage.airport.cdg': 'Aeroporto Parigi-CDG',
    'locationPage.airport.orly': 'Aeroporto Parigi-Orly',
    'locationPage.eiffel': 'Torre Eiffel',
    'locationPage.louvre': 'Museo del Louvre',
    'locationPage.champs': 'Campi Elisi',
    'locationPage.pantheon': 'Il Pantheon',
    
    // Breakfast
    'breakfast.badge': 'Al vostro servizio',
    'breakfast.title': 'Colazione & Bar',
    'breakfast.subtitle': 'La colazione che ti fa sorridere!',
    'breakfast.desc1': 'Ogni mattina, fai il pieno di energia con la nostra colazione completa, servita a buffet dolce e salato a volontà.',
    'breakfast.desc2': 'Nel menu: bevande calde, baguette tradizionali e cereali, paste croccanti, frutta fresca e cereali. Sul lato salato, uova sode, salumi, petto di tacchino, formaggi e yogurt naturali bio. E per i più golosi: marmellate e crepes morbide delicatamente vanilliate.',
    'breakfast.cta': 'Scopri la nostra colazione',
    'breakfast.bar.title': 'Un bar accogliente per rilassarsi',
    'breakfast.bar.desc1': 'In qualsiasi momento della giornata, accomodati al bar dell\'hotel per condividere un drink, chiacchierare o semplicemente fare una pausa.',
    'breakfast.bar.desc2': 'In un\'atmosfera accogliente e rilassata, è il luogo ideale per ritrovarsi dopo una giornata intensa.',
    
    // Breakfast Page
    'breakfastPage.badge': 'Ogni mattina',
    'breakfastPage.title': 'La colazione che ti fa sorridere!',
    'breakfastPage.intro1': 'Ogni mattina, fai il pieno di energia con la nostra colazione completa, servita a buffet dolce e salato a volontà.',
    'breakfastPage.intro2': 'Nel menu: bevande calde, baguette tradizionali e cereali, paste croccanti, frutta fresca e cereali. Sul lato salato, uova sode, salumi, petto di tacchino, formaggi e yogurt naturali bio. E per i più golosi: marmellate e crepes morbide delicatamente vanilliate.',
    'breakfastPage.enjoy': 'Tutto il necessario per iniziare bene la giornata, qualunque sia il tuo programma!',
    'breakfastPage.hours': 'Orari',
    'breakfastPage.hoursValue': '7:00 - 10:00',
    'breakfastPage.formula': 'Formula',
    'breakfastPage.formulaValue': 'Buffet a volontà',
    'breakfastPage.hotDrinks': 'Bevande calde',
    'breakfastPage.pastries': 'Paste',
    'breakfastPage.fruits': 'Frutta fresca',
    'breakfastPage.savory': 'Buffet salato',
    'breakfastPage.gallery': 'Galleria Foto',
    'breakfastPage.space': 'La nostra area colazione',
    'breakfastPage.view': 'Vedi',
    
    // Seminars
    'seminars.badge': 'Spazio professionale',
    'seminars.title': 'Sala seminari',
    'seminars.subtitle': 'Organizza le tue riunioni in modo diverso!',
    'seminars.desc1': "L'Hotel Inn Design Paris mette a disposizione diverse sale seminari moderne e completamente attrezzate: lavagna a fogli mobili, schermi con videoproiettore, microfoni e connessione wifi.",
    'seminars.desc2': 'A seconda dei tuoi obiettivi, diverse configurazioni sono possibili per adattarsi perfettamente alle tue riunioni, formazioni o eventi professionali.',
    'seminars.quote': 'Richiedi preventivo',
    'seminars.discover': 'Scopri le nostre sale',
    
    // Seminars Page
    'seminarsPage.badge': 'Seminari ed Eventi',
    'seminarsPage.title': 'Le nostre sale seminari',
    'seminarsPage.intro1': 'Organizza le tue riunioni, formazioni o eventi professionali nelle nostre sale moderne e modulabili, perfette per piccoli team o grandi delegazioni.',
    'seminarsPage.intro2': 'Dopo una giornata produttiva, i tuoi partecipanti potranno godere di camere confortevoli e aree relax.',
    'seminarsPage.intro3': 'Offriamo anche saloni modulabili per i vostri cocktail, banchetti o giornate di studio, il tutto in un ambiente pratico e piacevole.',
    'seminarsPage.equipment': 'Attrezzatura inclusa',
    'seminarsPage.projector': 'Videoproiettore',
    'seminarsPage.screen': 'Schermo di proiezione',
    'seminarsPage.wifi': 'Wi-Fi ad alta velocità',
    'seminarsPage.coffee': 'Pause caffè',
    'seminarsPage.modular': 'Configurazioni modulabili',
    'seminarsPage.catering': 'Servizio catering',
    'seminarsPage.spaces': 'I nostri spazi',
    'seminarsPage.meetingRooms': 'Sale riunioni',
    'seminarsPage.virtualTour': 'Tour Virtuale',
    'seminarsPage.videoTitle': 'Scopri i nostri spazi in video',
    'seminarsPage.cta.title': 'Richiedi un preventivo personalizzato',
    'seminarsPage.cta.subtitle': 'Il nostro team ti accompagna nell\'organizzazione del tuo evento',
    'seminarsPage.cta.button': 'Contattaci',
    'seminarsPage.uShape': 'A U',
    'seminarsPage.classroom': 'Classe',
    'seminarsPage.theatre': 'Teatro',
    
    // Events
    'events.badge': 'Eventi e Offerte',
    'events.title': 'Scopri la nostra agenda e offerte',
    'events.cta': 'Vedi tutti gli eventi',
    
    // Actualites Page
    'actualites.hero.badge': 'Eventi e Offerte',
    'actualites.hero.title': 'I nostri eventi e offerte esclusive',
    'actualites.hero.description': 'Scopri i prossimi eventi, concerti, promozioni e offerte speciali dell\'Hotel Inn Design Paris.',
    'actualites.readTime': 'di lettura',
    'actualites.learnMore': 'Scopri di più',
    'actualites.allEvents': 'Tutti gli eventi',
    'actualites.loadMore': 'Vedi altri eventi',
    'actualites.newsletter.title': 'Resta informato',
    'actualites.newsletter.description': 'Iscriviti alla nostra newsletter per ricevere le nostre ultime notizie e offerte esclusive.',
    'actualites.newsletter.placeholder': 'La tua email',
    'actualites.newsletter.button': 'Iscriviti',
    
    // Room booking button
    'rooms.bookButton': 'Prenota',
    
    // Seminar quote button
    'seminars.quoteButton': 'Richiedi preventivo',
    
    // Services Section
    'services.badge': 'Al vostro servizio',
    'services.title': 'Tutto per il vostro comfort',
    'services.reception.title': 'Reception & Info pratiche',
    'services.reception.247': 'Reception 24/7',
    'services.reception.checkin': 'Check-out prima delle 12 – Check-in dopo le 14',
    'services.reception.parking': 'Parcheggio privato e sicuro',
    'services.reception.luggage': 'Deposito bagagli gratuito',
    'services.reception.taxi': 'Taxi – Tariffa fissa aeroporto',
    'services.restaurant.title': 'Ristoranti nelle vicinanze',
    'services.restaurant.desc': 'Che cerchiate piatti locali e tradizionali, sapori internazionali esotici o cucina gourmet raffinata, è molto probabile che possiate trovare un ristorante adatto ai vostri desideri.',
    'services.tourism.title': 'Turismo',
    'services.tourism.desc': 'Durante il vostro soggiorno all\'Hotel Inn Design Place d\'Italie a Parigi, potrete immergervi nella storia della capitale francese: Le Catacombe di Parigi, La Torre Eiffel, Torre Montparnasse, Istituto del Mondo Arabo, Museo del Louvre, Pantheon...',
    
    // CTA
    'cta.badge': 'Miglior Prezzo Garantito',
    'cta.title': 'Più economico qui che altrove, garantito',
    'cta.subtitle': 'Nessuna piattaforma batterà il nostro prezzo!',
    'cta.description': 'Confronta tu stesso: non troverai mai un prezzo più basso che prenotando direttamente sul nostro sito. È la nostra promessa.',
    'cta.button': 'Prenota al miglior prezzo',
    'cta.contact': 'Contattaci',
    'cta.moreExpensive': 'Più caro',
    'cta.noAdvantages': 'Nessun vantaggio',
    'cta.bestPrice': 'Miglior tariffa',
    'cta.ourSite': 'Sito ufficiale',
    'cta.exclusiveAdvantages': 'vantaggi esclusivi',
    'cta.advantage1': '-15% garantito',
    'cta.advantage2': 'Vantaggi esclusivi',
    'cta.advantage3': 'Prenotazione sicura',
    
    // Contact Bubble
    'contact.bubble': 'Contattaci',
    
    // Footer
    'footer.description': 'Hotel 3 stelle nel cuore del 13° arrondissement, a due passi da Place d\'Italie.',
    'footer.navigation': 'Navigazione',
    'footer.contact': 'Contatto',
    'footer.rights': 'Tutti i diritti riservati.',
    'footer.legal': 'Note legali',
    'footer.privacy': 'Informativa privacy',
  },
  pt: {
    // Navigation
    'nav.hotel': 'O Hotel',
    'nav.home': 'Início',
    'nav.rooms': 'Quartos',
    'nav.breakfast': 'Café da manhã',
    'nav.seminars': 'Seminários',
    'nav.location': 'Localização',
    'nav.events': 'Eventos',
    'nav.contact': 'Contato',
    'nav.book': 'Reservar',
    
    // Hero
    'hero.welcome': 'Bem-vindo',
    'hero.name': 'Hotel Inn Design',
    'hero.location': "Place d'Italie",
    
    // Intro
    'intro.badge': 'Bem-vindo',
    'intro.title': 'Um hotel bem localizado para tudo!',
    'intro.description': "Situado no coração do 13º arrondissement, o Hotel Inn Design Paris desfruta de uma localização ideal, perto da Butte-aux-Cailles, parques e cais. Nosso hotel oferece 70 quartos confortáveis, um estacionamento privado e seguro, bem como um bar acolhedor e uma área de recepção propícia ao relaxamento ou trocas profissionais.",
    'intro.cta': 'Reserve seu quarto e aproveite sua estadia em Paris!',
    'intro.button': 'Reservar um quarto',
    'intro.stars': '3 estrelas',
    'intro.rooms': '70 quartos',
    'intro.parking': 'Estacionamento privado',
    'intro.bar': 'Bar acolhedor',
    
    // Rooms Section
    'rooms.badge': 'Nossos alojamentos',
    'rooms.title': 'Quartos & Suítes',
    'rooms.subtitle': 'Desfaça as malas e aproveite!',
    'rooms.description': 'Acomode-se em um dos nossos 70 quartos luminosos, à prova de som e totalmente equipados para o seu conforto.',
    'rooms.description2': 'Ar condicionado, TV de tela plana, escrivaninha, cofre, secador de cabelo, bandeja de cortesia... tudo é pensado para você.',
    'rooms.viewAll': 'Ver todos os quartos',
    'rooms.book': 'Reservar um quarto',
    'rooms.double': 'Quarto Duplo',
    'rooms.double.desc': 'Cama de 160×200 cm. Desfrute de um espaço elegante e confortável, ideal para uma estadia a dois ou sozinho.',
    'rooms.twin': 'Quarto Twin',
    'rooms.twin.desc': '2 camas de 100×200 cm. Perfeito para viagens com amigos ou colegas, com todo o conforto necessário.',
    'rooms.superior': 'Quarto Superior com varanda',
    'rooms.superior.desc': 'Desfrute de um espaço exterior privado com vista para Paris. Uma experiência única no coração da cidade.',
    'rooms.connecting': 'Quartos Comunicantes',
    'rooms.connecting.desc': '2 quartos moduláveis com portas comunicantes. A solução ideal para famílias ou grupos.',
    'rooms.bathroom': 'Banheiro privativo',
    'rooms.tv': 'TV tela plana',
    'rooms.desk': 'Escrivaninha',
    'rooms.wifi': 'Wi-Fi grátis',
    'rooms.courtesy': 'Bandeja de cortesia',
    'rooms.ac': 'Ar condicionado',
    
    // Rooms Page
    'roomsPage.badge': 'Nossos Alojamentos',
    'roomsPage.title': 'Os quartos do Hotel Inn Design Paris',
    'roomsPage.intro': 'Desfrute de 70 quartos luminosos, à prova de som e confortáveis, com banheiro equipado. Sozinho, em família ou com amigos, tudo é pensado para o seu bem-estar, com quartos comunicantes e uma equipe atenciosa. Localização ideal, o hotel é o ponto de partida perfeito para descobrir Paris sem estresse.',
    'roomsPage.ourRooms': 'Nossos alojamentos',
    'roomsPage.discover': 'Descubra nossos quartos',
    'roomsPage.gallery': 'Galeria de Fotos',
    'roomsPage.spaces': 'Descubra nossos espaços',
    'roomsPage.view': 'Ver',
    'roomsPage.cta.title': 'Reserve seu quarto agora',
    'roomsPage.cta.subtitle': 'Obtenha -15% reservando diretamente em nosso site',
    'roomsPage.cta.button': 'Ver disponibilidade',
    'roomsPage.double.name': 'Quarto Duplo',
    'roomsPage.double.details': 'Cama de 160×200 cm',
    'roomsPage.double.desc': 'Desfrute de um espaço elegante e confortável, ideal para uma estadia a dois ou sozinho. Equipado com todo o conforto moderno, este quarto oferece um refúgio de paz no coração de Paris.',
    'roomsPage.twin.name': 'Quarto Twin',
    'roomsPage.twin.details': '2 camas de 100×200 cm',
    'roomsPage.twin.desc': 'Perfeito para viagens com amigos ou colegas, com todo o conforto necessário. Duas camas separadas em um espaço otimizado para uma estadia agradável.',
    'roomsPage.superior.name': 'Quarto Superior com Varanda',
    'roomsPage.superior.details': 'Vista de Paris',
    'roomsPage.superior.desc': 'Desfrute de um espaço exterior privado com vista para Paris. Uma experiência única no coração da cidade. Ideal para saborear o café da manhã admirando os telhados parisienses.',
    'roomsPage.connecting.name': 'Quartos Comunicantes',
    'roomsPage.connecting.details': '2 quartos moduláveis',
    'roomsPage.connecting.desc': 'Dois quartos com portas comunicantes, a solução ideal para famílias ou grupos. Desfrute da privacidade de quartos separados mantendo-se conectados.',
    
    // About / Location
    'about.badge': 'Localização ideal',
    'about.title': 'Um hotel no coração de Paris',
    'about.description': 'O Hotel Inn Paris fica a 2 minutos a pé do metrô parisiense e oferece grande comodidade.',
    'about.metro': 'Acesso metrô (saída 3)',
    
    // Location Section (Homepage)
    'location.badge': 'Como nos encontrar',
    'location.title': 'Localização',
    'location.access': 'Acesso',
    'location.metro': 'Metrô',
    'location.bus': 'Ônibus',
    'location.tramway': 'Tramway',
    'location.parking': 'Estacionamento privado seguro disponível mediante reserva.',
    
    // Location Page
    'locationPage.badge': 'Encontre-nos',
    'locationPage.title': 'Nossa localização',
    'locationPage.openMaps': 'Abrir no Google Maps',
    'locationPage.idealLocation': 'Localização ideal',
    'locationPage.heartOfParis': 'Um hotel no coração de Paris',
    'locationPage.heartDesc': 'A poucos passos do metrô Place d\'Italie, desfrute de acesso rápido a todos os monumentos e atrações da capital.',
    'locationPage.parking': 'Estacionamento',
    'locationPage.parkingDesc': 'Estacionamento privado seguro (€15/dia)',
    'locationPage.reception': 'Recepção',
    'locationPage.receptionDesc': 'Aberta 24/7',
    'locationPage.needDirections': 'Precisa de direções?',
    'locationPage.airport.cdg': 'Aeroporto Paris-CDG',
    'locationPage.airport.orly': 'Aeroporto Paris-Orly',
    'locationPage.eiffel': 'Torre Eiffel',
    'locationPage.louvre': 'Museu do Louvre',
    'locationPage.champs': 'Champs-Élysées',
    'locationPage.pantheon': 'O Pantheon',
    
    // Breakfast
    'breakfast.badge': 'Ao seu serviço',
    'breakfast.title': 'Café da manhã & Bar',
    'breakfast.subtitle': 'O café da manhã que faz você sorrir!',
    'breakfast.desc1': 'Todas as manhãs, recarregue suas energias com nosso café da manhã completo, servido em buffet doce e salgado à vontade.',
    'breakfast.desc2': 'No cardápio: bebidas quentes, baguetes tradicionais e cereais, croissants crocantes, frutas frescas e cereais. No lado salgado, ovos cozidos, frios, peito de peru, queijos e iogurtes naturais orgânicos. E para os mais gulosos: geleias e panquecas macias delicadamente baunilhadas.',
    'breakfast.cta': 'Descobrir nosso café da manhã',
    'breakfast.bar.title': 'Um bar acolhedor para relaxar',
    'breakfast.bar.desc1': 'A qualquer hora do dia, sente-se no bar do hotel para compartilhar uma bebida, conversar ou simplesmente fazer uma pausa.',
    'breakfast.bar.desc2': 'Em um ambiente acolhedor e descontraído, é o lugar ideal para se reunir após um dia agitado.',
    
    // Breakfast Page
    'breakfastPage.badge': 'Todas as manhãs',
    'breakfastPage.title': 'O café da manhã que faz você sorrir!',
    'breakfastPage.intro1': 'Todas as manhãs, recarregue suas energias com nosso café da manhã completo, servido em buffet doce e salgado à vontade.',
    'breakfastPage.intro2': 'No cardápio: bebidas quentes, baguetes tradicionais e cereais, croissants crocantes, frutas frescas e cereais. No lado salgado, ovos cozidos, frios, peito de peru, queijos e iogurtes naturais orgânicos. E para os mais gulosos: geleias e panquecas macias delicadamente baunilhadas.',
    'breakfastPage.enjoy': 'Tudo o que você precisa para começar bem o dia, seja qual for o seu programa!',
    'breakfastPage.hours': 'Horários',
    'breakfastPage.hoursValue': '7:00 - 10:00',
    'breakfastPage.formula': 'Fórmula',
    'breakfastPage.formulaValue': 'Buffet à vontade',
    'breakfastPage.hotDrinks': 'Bebidas quentes',
    'breakfastPage.pastries': 'Croissants',
    'breakfastPage.fruits': 'Frutas frescas',
    'breakfastPage.savory': 'Buffet salgado',
    'breakfastPage.gallery': 'Galeria de Fotos',
    'breakfastPage.space': 'Nossa área de café da manhã',
    'breakfastPage.view': 'Ver',
    
    // Seminars
    'seminars.badge': 'Espaço profissional',
    'seminars.title': 'Sala de seminários',
    'seminars.subtitle': 'Organize suas reuniões de forma diferente!',
    'seminars.desc1': 'O Hotel Inn Design Paris disponibiliza várias salas de seminário modernas e totalmente equipadas: flipchart, telas com projetor de vídeo, microfones e conexão wifi.',
    'seminars.desc2': 'Dependendo dos seus objetivos, diferentes configurações são possíveis para se adaptar perfeitamente às suas reuniões, treinamentos ou eventos profissionais.',
    'seminars.quote': 'Solicitar orçamento',
    'seminars.discover': 'Descobrir nossas salas',
    
    // Seminars Page
    'seminarsPage.badge': 'Seminários e Eventos',
    'seminarsPage.title': 'Nossas salas de seminário',
    'seminarsPage.intro1': 'Organize suas reuniões, treinamentos ou eventos profissionais em nossas salas modernas e moduláveis, perfeitas para pequenas equipes ou grandes delegações.',
    'seminarsPage.intro2': 'Após um dia produtivo, seus participantes poderão desfrutar de quartos confortáveis e áreas de descanso.',
    'seminarsPage.intro3': 'Também oferecemos salões moduláveis para seus coquetéis, banquetes ou jornadas de estudo, tudo em um ambiente prático e agradável.',
    'seminarsPage.equipment': 'Equipamentos incluídos',
    'seminarsPage.projector': 'Projetor de vídeo',
    'seminarsPage.screen': 'Tela de projeção',
    'seminarsPage.wifi': 'Wi-Fi de alta velocidade',
    'seminarsPage.coffee': 'Pausas para café',
    'seminarsPage.modular': 'Configurações moduláveis',
    'seminarsPage.catering': 'Serviço de catering',
    'seminarsPage.spaces': 'Nossos espaços',
    'seminarsPage.meetingRooms': 'Salas de reunião',
    'seminarsPage.virtualTour': 'Tour Virtual',
    'seminarsPage.videoTitle': 'Descubra nossos espaços em vídeo',
    'seminarsPage.cta.title': 'Solicite um orçamento personalizado',
    'seminarsPage.cta.subtitle': 'Nossa equipe acompanha você na organização do seu evento',
    'seminarsPage.cta.button': 'Entre em contato',
    'seminarsPage.uShape': 'Em U',
    'seminarsPage.classroom': 'Classe',
    'seminarsPage.theatre': 'Teatro',
    
    // Events
    'events.badge': 'Eventos e Ofertas',
    'events.title': 'Descubra nossa agenda e ofertas',
    'events.cta': 'Ver todos os eventos',
    
    // Actualites Page
    'actualites.hero.badge': 'Eventos e Ofertas',
    'actualites.hero.title': 'Nossos eventos e ofertas exclusivas',
    'actualites.hero.description': 'Descubra os próximos eventos, shows, promoções e ofertas especiais do Hotel Inn Design Paris.',
    'actualites.readTime': 'de leitura',
    'actualites.learnMore': 'Saiba mais',
    'actualites.allEvents': 'Todos os eventos',
    'actualites.loadMore': 'Ver mais eventos',
    'actualites.newsletter.title': 'Fique informado',
    'actualites.newsletter.description': 'Inscreva-se em nossa newsletter para receber nossas últimas notícias e ofertas exclusivas.',
    'actualites.newsletter.placeholder': 'Seu email',
    'actualites.newsletter.button': 'Inscrever-se',
    
    // Room booking button
    'rooms.bookButton': 'Reservar',
    
    // Seminar quote button
    'seminars.quoteButton': 'Solicitar orçamento',
    
    // Services Section
    'services.badge': 'Ao seu serviço',
    'services.title': 'Tudo para o seu conforto',
    'services.reception.title': 'Recepção & Informações práticas',
    'services.reception.247': 'Recepção 24/7',
    'services.reception.checkin': 'Check-out antes das 12h – Check-in após as 14h',
    'services.reception.parking': 'Estacionamento privado e seguro',
    'services.reception.luggage': 'Guarda-volumes gratuito',
    'services.reception.taxi': 'Táxi – Tarifa fixa aeroporto',
    'services.restaurant.title': 'Restaurantes próximos',
    'services.restaurant.desc': 'Seja procurando pratos locais e tradicionais, sabores internacionais exóticos ou culinária gourmet refinada, é muito provável que você encontre um restaurante adequado aos seus desejos.',
    'services.tourism.title': 'Turismo',
    'services.tourism.desc': 'Durante sua estadia no Hotel Inn Design Place d\'Italie em Paris, você poderá mergulhar na história da capital francesa: As Catacumbas de Paris, A Torre Eiffel, Torre Montparnasse, Instituto do Mundo Árabe, Museu do Louvre, Panteão...',
    
    // CTA
    'cta.badge': 'Melhor Preço Garantido',
    'cta.title': 'Mais barato aqui do que em qualquer outro lugar',
    'cta.subtitle': 'Nenhuma plataforma vai bater nosso preço!',
    'cta.description': 'Compare você mesmo: você nunca encontrará um preço mais baixo do que reservando diretamente em nosso site. É nossa promessa.',
    'cta.button': 'Reservar ao melhor preço',
    'cta.contact': 'Entre em contato',
    'cta.moreExpensive': 'Mais caro',
    'cta.noAdvantages': 'Sem vantagens',
    'cta.bestPrice': 'Melhor tarifa',
    'cta.ourSite': 'Site oficial',
    'cta.exclusiveAdvantages': 'vantagens exclusivas',
    'cta.advantage1': '-15% garantido',
    'cta.advantage2': 'Vantagens exclusivas',
    'cta.advantage3': 'Reserva segura',
    
    // Contact Bubble
    'contact.bubble': 'Fale conosco',
    
    // Footer
    'footer.description': 'Hotel 3 estrelas no coração do 13º arrondissement, a poucos passos da Place d\'Italie.',
    'footer.navigation': 'Navegação',
    'footer.contact': 'Contato',
    'footer.rights': 'Todos os direitos reservados.',
    'footer.legal': 'Avisos legais',
    'footer.privacy': 'Política de privacidade',
  },
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('fr');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
